### PR TITLE
Adds infilling script to repo

### PR DESCRIPTION
**Pull request by jameshiebert**
This script can be used to infill some missed data for any set of
networks that are available in crmprtd. The script is minimally
configurable for ease of use. Simply give it a start time and end
time, and based on the network, it will compute whether it can make a
request for that time range. If it can, it will go out and download
all of the data for that time range, and the process it into the
database.

Only four parameters are required: a start time, end time, auth
details (for MoTI and WMB) and a database connection. Optionally you
can configure the loggging, and select a subset of available networks
to infill.

### CODE REVIEW

**Comment by jameshiebert** [comment]
@faronium This is the script that I mentioned yesterday. I've used this to infill the three gaps that we had this month and it works pretty well. It's a bit slow, but it's easy and comprehensive. Let me know if you have any comments or suggestions.

**Comment by faronium** [comment]
Quick question about this James: I recall that the script hits the crontab to see what the relevant backfills are. When I add the second line for MoTI in the crontab for the new BCeID user, will that cause duplicate efforts in your script's backfilling? I guess it may not matter as the DB inserts will yield skips. I'm going to insert the new crontab line now, but let me know if it causes issues.

**Comment by jameshiebert** [comment]
No, this script doesn't actually *use* the crontab, it simply mimics it based on manually translating requirements during development. Plus it doesn't use the default request for MoTI, because it's infilling over a range. So it queries the databases for all stations available and then sends a request for each station for each week in the time range. See [here](https://github.com/pacificclimate/crmprtd/pull/59/files#diff-ca213eb04ecbb893668df3c02241c8c7R129) for the code.

**Comment by faronium** [comment]
Okay, cool. Looks like a nice byproduct of building flexible and general tools :-)

Have you tested it on MoTI? Looks like the time string that gets passed to the URL may have the incorrect form :-/ I see that the format string passed to strftime is set for all networks as:

    time_fmt = '%Y/%m/%d %H:%M:%S'
needs:
   time_fmt = '%Y-%m-%d/%H'

Sorry, I feel like I'm being an ass.

**Comment by jameshiebert** [comment]
> Sorry, I feel like I'm being an ass.

No, that's a fair question and good to double check.

Actually all of the download scripts take a standardized time format, and each individual download script translates the format to what it needs to be for that network. If you look at the help for `download_moti` you can see what it takes:

```
$ download_moti --help
usage: download_moti [-h] [-L LOG_CONF] [-l LOG_FILENAME]
                     [-o {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [-m ERROR_EMAIL]
                     [--auth_fname AUTH_FNAME] [--auth_key AUTH_KEY]
                     [--username USERNAME] [--password PASSWORD]
                     [-S START_TIME] [-E END_TIME] [-s STATION_ID]

Downloads the BC Ministry of Transportation and Infrastructure (MoTI) data.
The BC Ministry of Transportation and Infrastructure, Avalache Safety Program
network has an application which returns meteorological data upon request. By
default the application returns all data available from the previous hour. It
*is* possible to request any data, however the time range is limited to 7 days
and you need to explicitly limit the query to a specific station id. I.e. you
cannot specify a time range without a priori information. Also see:
https://github.com/pacificclimate/crmprtd/issues/52. It is recommend to run
this script, time parameter free every hour to collect the bulk of the data.
It is further recommended to do an additional run once per one or two weeks
with the aid of a station list to fill in any gaps that may have arisen from
outages or data that came in late. Gaps can be filled in at any time, so there
is little risk of missing data.

optional arguments:
  -h, --help            show this help message and exit
  -L LOG_CONF, --log_conf LOG_CONF
                        YAML file to use to override the default logging
                        configuration
  -l LOG_FILENAME, --log_filename LOG_FILENAME
                        Override the default log filename
  -o {DEBUG,INFO,WARNING,ERROR,CRITICAL}, --log_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set log level: DEBUG, INFO, WARNING, ERROR, CRITICAL.
                        Note that debug output by default goes directly to
                        file
  -m ERROR_EMAIL, --error_email ERROR_EMAIL
                        Override the default e-mail address to which the
                        program should report critical errors
  --auth_fname AUTH_FNAME
                        Yaml file with plaintext usernames/passwords
  --auth_key AUTH_KEY   Top level key which user/pass are stored in yaml file.
  --username USERNAME   The username for data requests. Overrides auth file.
  --password PASSWORD   The password for data requests. Overrides auth file.
  -S START_TIME, --start_time START_TIME
                        Alternate time to use for downloading (interpreted
                        with strptime(format='Y/m/d H:M:S'). Defaults to one
                        hour prior to now
  -E END_TIME, --end_time END_TIME
                        Alternate time to use for downloading (interpreted
                        with strptime(format='Y/m/d H:M:S'). Defaults to now.
  -s STATION_ID, --station_id STATION_ID
                        Station ID for which to download data
```

But yes, I've tested it for all networks and it works swimmingly.

**Comment by faronium** [comment]
Sweet. Thanks!

**Comment by jameshiebert** [comment]
I think that I've addressed all feedback on this PR, so I'm going to go ahead and merge this and make it ready for production use.

**Pull request merged**
